"""removed cappitalization in position column

Revision ID: 279e1ea8ab92
Revises: 18ab3aeaedcc
Create Date: 2025-09-06 06:34:21.148889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '279e1ea8ab92'
down_revision: Union[str, Sequence[str], None] = '18ab3aeaedcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_memberships', sa.Column('position', sa.String(length=100), nullable=True))
    op.drop_column('office_memberships', 'Position')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('office_memberships', sa.Column('Position', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('office_memberships', 'position')
    # ### end Alembic commands ###
