"""is active column is added

Revision ID: 6e44bc54f768
Revises: cf2632a1eeab
Create Date: 2025-08-31 14:56:49.854629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e44bc54f768'
down_revision: Union[str, Sequence[str], None] = 'cf2632a1eeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offices', sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('offices', 'is_active')
    # ### end Alembic commands ###
